// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RL10fv2TlsGr5IuHLQab4hJa9OjHxEs',
    appId: '1:289883860881:web:ff5ef98ecca636f9bd7430',
    messagingSenderId: '289883860881',
    projectId: 'cem5n6-tp-desilets',
    authDomain: 'cem5n6-tp-desilets.firebaseapp.com',
    storageBucket: 'cem5n6-tp-desilets.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xFnMJ-F9k4sGCthL-uKoE9UQQ_lBrbM',
    appId: '1:289883860881:android:267dd3ae9d108c52bd7430',
    messagingSenderId: '289883860881',
    projectId: 'cem5n6-tp-desilets',
    storageBucket: 'cem5n6-tp-desilets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6NMgcp8enHWs_wwthugXPVhdJJUg344Q',
    appId: '1:289883860881:ios:5a5be051d8fa890dbd7430',
    messagingSenderId: '289883860881',
    projectId: 'cem5n6-tp-desilets',
    storageBucket: 'cem5n6-tp-desilets.firebasestorage.app',
    iosBundleId: 'com.example.tp3AppmobilesDesilets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6NMgcp8enHWs_wwthugXPVhdJJUg344Q',
    appId: '1:289883860881:ios:5a5be051d8fa890dbd7430',
    messagingSenderId: '289883860881',
    projectId: 'cem5n6-tp-desilets',
    storageBucket: 'cem5n6-tp-desilets.firebasestorage.app',
    iosBundleId: 'com.example.tp3AppmobilesDesilets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4RL10fv2TlsGr5IuHLQab4hJa9OjHxEs',
    appId: '1:289883860881:web:492d106870795f2cbd7430',
    messagingSenderId: '289883860881',
    projectId: 'cem5n6-tp-desilets',
    authDomain: 'cem5n6-tp-desilets.firebaseapp.com',
    storageBucket: 'cem5n6-tp-desilets.firebasestorage.app',
  );

}